// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edmssetawhjpeurzwadc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbXNzZXRhd2hqcGV1cnp3YWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2Mzk2NDUsImV4cCI6MjA5MzIxNTY0NX0.7xwOvj54_6Uaa8wa4GT_S8JkSpJSVhfwW79sBxH3c1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});